language: objective-c

osx_image: xcode8.2

script:
- travis_retry xcodebuild clean build -project Uno.xcodeproj -scheme Uno CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- travis_retry xcodebuild test -project Uno.xcodeproj -scheme UnoTests -destination 'platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72,OS=10.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
