language: objective-c

branches:
only:
- master

#- xcodebuild test -project Uno.xcodeproj -scheme UnoTests -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2'
#- xcodebuild clean build -project Uno.xcodeproj -scheme Uno -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3'
script:
- xcodebuild clean build -project Uno.xcodeproj -scheme Uno CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
